version: "3"
services:
  www:
      image: nginx:alpine
      volumes:
          - ./etc/nginx/conf.d/default.conf.nginx:/etc/nginx/conf.d/default.conf
      ports:
          - 81:80
      depends_on:
          - backend
          - frontend

  frontend:
      image: node:current-alpine
      working_dir: /home/node/app
      volumes:
          - ./frontend:/home/node/app
      environment:
          NODE_ENV: development
      expose:
        - "8000"
      command: "npm run dev"

  backend:
      build:
        args:
          user: sammy
          uid: 1000
        context: etc/dockerize/backend
      expose:
        - "8080"
      volumes:
          - ./backend:/var/www
          - ./etc/php:/usr/local/etc/php/local.conf.d/
      environment:
          # add our custom config files for the php to scan
          PHP_INI_SCAN_DIR: "/usr/local/etc/php/conf.d/:/usr/local/etc/php/local.conf.d/"
      command: "php artisan serve --host=0.0.0.0 --port=8080"
      depends_on:
        - db

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        
